# Generated by Django 4.1.7 on 2023-03-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_result_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='standard',
            field=models.CharField(max_length=12, unique=True, verbose_name='class'),
        ),
    ]
